# Deep Learning Basics with PyTorch
## Part II — Neural Networks and PyTorch Basics
## Chapter 5 — The Limits of Classical ML

#### Overview
This notebook provides a concise, hands-on walkthrough of Deep Learning Basics with PyTorch. Use it as a companion to the chapter: run each cell, read the short notes, and try small variations to build intuition.

**Tips:**

- Run cells top to bottom; restart kernel if state gets confusing.
- Prefer small, fast experiments; iterate quickly and observe outputs.
- Keep an eye on shapes, dtypes, and devices when using PyTorch.

In [1]:
 # !pip -q install torch numpy matplotlib
import torch, numpy as np, matplotlib.pyplot as plt
plt.style.use('seaborn-v0_8')  # plotting
%config InlineBackend.figure_format = 'retina'

## Tensors: creation, shapes, dtypes, devices

In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32)
x, x.shape, x.dtype, x.device

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]),
 torch.float32,
 device(type='cpu'))

In [3]:
x.mean(dim = 0), x.mean(dim = 1), x.T

(tensor([2.5000, 3.5000, 4.5000]),
 tensor([2., 5.]),
 tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]))

## NumPy interop (zero-copy on CPU)

In [4]:
a = np.arange(6, dtype = np.float32).reshape(2, 3)
t = torch.from_numpy(a)
a*= 10
t

tensor([[ 0., 10., 20.],
        [30., 40., 50.]])

In [5]:
u = t.numpy()
t += 1
u

array([[ 1., 11., 21.],
       [31., 41., 51.]], dtype=float32)

## Broadcasting demo

In [6]:
a = torch.arange(3.).reshape(3, 1)
b = torch.arange(4.).reshape(1, 4)
c = a+b
c, c.shape

(tensor([[0., 1., 2., 3.],
         [1., 2., 3., 4.],
         [2., 3., 4., 5.]]),
 torch.Size([3, 4]))

## Autograd: scalar gradient

In [7]:
w = torch.tensor(4.5, requires_grad = True)
f = (w - 2)**2
f.backward()
  # Use .detach().item() to safely convert to Python scalars without autograd warnings
w_val = w.detach().item()
f_val = f.detach().item()
g_val = w.grad.item()
w_val, f_val, g_val

(4.5, 6.25, 5.0)

In [8]:
with torch.no_grad():
    w -= 0.3 * w.grad
    w.grad.zero_()
    print(w.detach().item())  # Show the updated parameter value explicitly

3.0
