# Chapter 5 Exercises
## Part II - Neural Networks and PyTorch Basics

These exercises reinforce the first PyTorch ideas from Chapter 5: tensors, shapes, interop, broadcasting, autograd, and manual parameter updates.


In [1]:
import numpy as np
import torch

np.random.seed(0)
torch.manual_seed(0)


## Warm-Up (brief)

Start by checking your PyTorch version and the device you will use. For this notebook, the main goal is simply to confirm that tensors can be created and inspected.


In [2]:
if torch.cuda.is_available():
    device = "cuda"
elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

x = torch.tensor([1.0, 2.0, 3.0], device=device)
print("torch version:", torch.__version__)
print("device:", device)
print("sample tensor:", x)


torch version: 2.9.1
device: mps
sample tensor: 

tensor([1., 2., 3.], device='mps:0')


## Exercise 1: Tensors and Interop

Create tensors from Python or NumPy data, then observe how NumPy and PyTorch can share memory on CPU.


In [3]:
a_np = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float32)
t = torch.from_numpy(a_np)

print("tensor shape:", t.shape)
print("tensor dtype:", t.dtype)
print("tensor device:", t.device)

a_np[0, 0] = 99.0
print("after editing NumPy:")
print(t)

u = t.numpy()
t[1, 1] = -5.0
print("after editing Tensor:")
print(u)


tensor shape: torch.Size([2, 3])
tensor dtype: torch.float32
tensor device: cpu
after editing NumPy:
tensor([[99.,  2.,  3.],
        [ 4.,  5.,  6.]])
after editing Tensor:
[[99.  2.  3.]
 [ 4. -5.  6.]]


## Exercise 2: Broadcasting

Use broadcasting to combine tensors with compatible shapes and verify the output shape.


In [4]:
a = torch.arange(3.0).reshape(3, 1)
b = torch.arange(4.0).reshape(1, 4)
c = a + b

print("a shape:", a.shape)
print("b shape:", b.shape)
print("c shape:", c.shape)
print(c)


a shape: torch.Size([3, 1])
b shape: torch.Size([1, 4])
c shape: torch.Size([3, 4])
tensor([[0., 1., 2., 3.],
        [1., 2., 3., 4.],
        [2., 3., 4., 5.]])


## Exercise 3: Autograd

Work through one scalar example and one vector example. Pay attention to the tensor value, the scalar loss, and the gradient that PyTorch computes.


In [5]:
x = torch.tensor(5.0, requires_grad=True)
loss = (x - 2.0) ** 2
loss.backward()

print("scalar x:", x.detach().item())
print("scalar loss:", loss.detach().item())
print("scalar gradient:", x.grad.item())

v = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
vector_loss = (v ** 2).sum()
vector_loss.backward()

print("vector v:", v.detach())
print("vector loss:", vector_loss.detach().item())
print("vector gradient:", v.grad)


scalar x: 5.0
scalar loss: 9.0
scalar gradient: 6.0
vector v: tensor([1., 2., 3.])
vector loss: 14.0
vector gradient: tensor([2., 4., 6.])


## Exercise 4: Manual Gradient Descent

Take a few manual optimization steps on a single parameter and watch how the parameter, loss, and gradient change.


In [6]:
w = torch.tensor(4.5, requires_grad=True)
learning_rate = 0.3

for step in range(3):
    loss = (w - 2.0) ** 2
    loss.backward()
    print(f"step {step}: w={w.detach().item():.3f}, loss={loss.detach().item():.3f}, grad={w.grad.item():.3f}")
    with torch.no_grad():
        w -= learning_rate * w.grad
    print(f"        updated w={w.detach().item():.3f}")
    w.grad.zero_()


step 0: w=4.500, loss=6.250, grad=5.000
        updated w=3.000
step 1: w=3.000, loss=1.000, grad=2.000
        updated w=2.400
step 2: w=2.400, loss=0.160, grad=0.800
        updated w=2.160


## Exercise 5: torch.no_grad()

Compare an update computed normally with one computed inside `torch.no_grad()` so you can see why parameter updates are usually excluded from gradient tracking.


In [7]:
w = torch.tensor(2.0, requires_grad=True)
loss = (w - 5.0) ** 2
loss.backward()

tracked_update = w - 0.1 * w.grad
with torch.no_grad():
    plain_update = w - 0.1 * w.grad

print("tracked update requires_grad:", tracked_update.requires_grad)
print("tracked update grad_fn:", tracked_update.grad_fn)
print("no_grad update requires_grad:", plain_update.requires_grad)
print("no_grad update grad_fn:", plain_update.grad_fn)


tracked update requires_grad: True
tracked update grad_fn: <SubBackward0 object at 0x120026e60>
no_grad update requires_grad: False
no_grad update grad_fn: None


## Key Takeaways

- Tensors carry values, shapes, dtypes, and devices.
- NumPy and PyTorch can share CPU memory, so changes may appear in both objects.
- Broadcasting expands compatible shapes without manual copying.
- Autograd computes gradients once a scalar loss is defined.
- Manual updates and `torch.no_grad()` are the bridge to later training loops.
